### ISSUE TITLE
jsonstreams does not make compact JSON

### ISSUE THREAD

**Issue by JonoYang** [dcbaker/jsonstreams#21]
I am having trouble getting jsonstreams to create compact JSON. I am calling `jsonstreams.Stream` without any "pretty" arguments (no `indent`, or `pretty`) (https://github.com/nexB/scancode-toolkit/blob/2303-stream-json-output/src/formattedcode/output_json.py#L118) and the resulting JSON is not compact and is on multiple lines:

```
{"headers": [
{
"tool_name": "scancode-toolkit",
"tool_version": "3.2.2rc3.post19.1a96002a2",
"options": {
"input": [
"README.rst"
],
"--info": true,
"--json": "-"
},
"notice": "Generated with ScanCode and provided on an \"AS IS\" BASIS, WITHOUT WARRANTIES\nOR CONDITIONS OF ANY KIND, either express or implied. No content created from\nScanCode should be considered or used as legal advice. Consult an Attorney\nfor any legal advice.\nScanCode is a free software code scanning tool from nexB Inc. and others.\nVisit https://github.com/nexB/scancode-toolkit/ for support and download.",
"start_timestamp": "2020-10-29T200445.839966",
"end_timestamp": "2020-10-29T200445.952883",
"duration": 0.11294198036193848,
"message": null,
"errors": [],
"extra_data": {
"files_count": 1
}
}
], "files": [
{
"path": "README.rst",
"type": "file",
"name": "README.rst",
...
```

I expect the output to be on a single line, as shown:
```
{"headers": [{"tool_name": "scancode-toolkit", "tool_version": "3.2.2rc3.post19.1a96002a2", "options": {"input": ["README.rst"], "--info": true, "--json": "-"}, "notice": "Generated with ScanCode and provided on an \"AS IS\" BASIS, WITHOUT WARRANTIES\nOR CONDITIONS OF ANY KIND, either express or implied. No content created from\nScanCode should be considered or used as legal advice. Consult an Attorney\nfor any legal advice.\nScanCode is a free software code scanning tool from nexB Inc. and others.\nVisit https://github.com/nexB/scancode-toolkit/ for support and download.", "start_timestamp": "2020-10-29T201342.141342", "end_timestamp": "2020-10-29T201342.254501", "duration": 0.11318397521972656, "message": null, "errors": [], "extra_data": {"files_count": 1}}], "files": [{"path": "README.rst", "type": "file", "name": "README.rst", "base_name": "README", "extension": ".rst", "size": 9901, "date": "2020-10-23", "sha1": "d95f7aab354edd715c32772d10afb79d99ff6281", "md5": "846b9f56b4c6984a818fdaa43bdd599f", "sha256": "61efb729d90a18599e9394cd99b9de8c96a99022aa097a9fd6e37fa3c329f31e", "mime_type": "text/plain", "file_type": "ASCII text", "programming_language": null, "is_binary": false, "is_text": true, "is_archive": false, "is_media": false, "is_source": false, "is_script": false, "files_count": 0, "dirs_count": 0, "size_count": 0, "scan_errors": []}]}
```

Thanks to @pombredanne, we were able to find out why `jsonstreams.Stream` was not creating compact JSON.

The issue has to do with `jsonstreams.Stream` using `indent=0` on https://github.com/dcbaker/jsonstreams/blob/master/jsonstreams/__init__.py#L540 and it is getting passed to `json.JSONEncoder` at https://github.com/dcbaker/jsonstreams/blob/master/jsonstreams/__init__.py#L192

According to https://docs.python.org/3/library/json.html#json.JSONEncoder, if `indent=0`, new lines will be inserted:
```
If indent is a non-negative integer or string, then JSON array elements and
object members will be pretty-printed with that indent level. An indent level of
0, negative, or "" will only insert newlines. None (the default) selects the
most compact representation. Using a positive integer indent indents that many
spaces per level. If indent is a string (such as "\t"), that string is used to
indent each level.
```

In an attempt to get around this, I passed the argument `indent=None` when instantiating `jsonstreams.Stream`, and I get an error:

```
Traceback (most recent call last):
  File "/home/jono/nexb/src/scancode-toolkit-new/src/scancode/cli.py", line 986, in run_codebase_plugins
    plugin.process_codebase(codebase, **kwargs)
  File "/home/jono/nexb/src/scancode-toolkit-new/src/formattedcode/output_json.py", line 96, in process_codebase
    write_results(codebase, output_file=output_json, pretty=False, **kwargs)
  File "/home/jono/nexb/src/scancode-toolkit-new/src/formattedcode/output_json.py", line 178, in write_results
    s._Stream__inst.close()
  File "/home/jono/nexb/src/scancode-toolkit-new/lib/python2.7/site-packages/jsonstreams/__init__.py", line 378, in close
    self._writer.raw_write('}', indent=True)
  File "/home/jono/nexb/src/scancode-toolkit-new/lib/python2.7/site-packages/jsonstreams/__init__.py", line 151, in raw_write
    self.fd.write(self._indent())
  File "/home/jono/nexb/src/scancode-toolkit-new/lib/python2.7/site-packages/jsonstreams/__init__.py", line 147, in _indent
    return ' ' * self.baseindent * self.indent
TypeError: can't multiply sequence by non-int of type 'NoneType'
```

I changed https://github.com/dcbaker/jsonstreams/blob/master/jsonstreams/__init__.py#L146 to look like:
```
    def _indent(self):
        if self.indent and isinstance(self.indent, int) and self.indent >= 0:
            return ' ' * self.baseindent * self.indent
        else:
            return ''
```

and then `jsonstreams.Stream` was able to create compact JSON in a single line.

**Comment by dcbaker** [comment]
I think this is can be closed now that #22 is merged? reopen if not please.
